/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
    docs: [
      {
        type: 'autogenerated',
        dirName: '.', // 👈 génère depuis tous les fichiers du dossier `docs/`
      },
    ],
  };
  
  